$axure.loadCurrentPage({
  "url":"订单详细（新建）买家.html",
  "generationDate":new Date(1408595825763.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e799bc59d34049c685f97bc1942fbc46",
    "type":"Axure:Page",
    "name":"订单详细（新建）买家",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d0975820f4243d3aba87a5ac568c933",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"9b1c42a66edf4a6abb033a6118044ec5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":66,
              "y":147},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f023fba5f3b64e13922492205ad5c387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":66,
                  "y":147},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u21.png"}},
{
          "id":"4b62b9f0c1b14892a1f82fc173c88241",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":60,
              "y":148},
            "size":{
              "width":33,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab25497c5eba45578608d200073e7deb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":60,
                  "y":148},
                "size":{
                  "width":33,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单一览",
                      "target":{
                        "targetType":"page",
                        "url":"订单一览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的预购订单/u15.png"}},
{
          "id":"83e51bf44a3f47258e2cf3af1beb2ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":93,
              "y":152},
            "size":{
              "width":28,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcf8b44272264b079ce86ee25bed0339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":93,
                  "y":152},
                "size":{
                  "width":28,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee05022fe1c44eeaac439912b3063633",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":66,
              "y":187},
            "size":{
              "width":322,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f7afe965bcd47cc9e132d1a1e01aa6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":66,
                  "y":187},
                "size":{
                  "width":322,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（新建）买家/u19.png"}},
{
          "id":"9f9ab6f8df334d6ab522ec253e1c9881",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":156,
              "y":193},
            "size":{
              "width":115,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1336718b54e49f2b4a444fed339e599",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":156,
                  "y":193},
                "size":{
                  "width":115,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单一览/u24.png"}},
{
          "id":"6d535a454f0f4b809d968fd959e89496",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":139,
              "y":309},
            "size":{
              "width":158,
              "height":21},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1494d8ee452a4642bba70ec31d63a6a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":139,
                  "y":309},
                "size":{
                  "width":158,
                  "height":21},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb1773f3c5304dc0be10d77dad8b56d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":66,
              "y":335},
            "size":{
              "width":320,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"105e650cecd8419292b3ac41479ad240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":66,
                  "y":335},
                "size":{
                  "width":320,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（新建）买家/u25.png"}},
{
          "id":"2857b2e5607946c3979f85e67c277e60",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":161,
              "y":543},
            "size":{
              "width":110,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83143ed265444f75aef6982f420282f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":161,
                  "y":543},
                "size":{
                  "width":110,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的预购订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的预购订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单详细（新建）买家/button_u27.png",
            "mouseOver~":"images/订单详细（新建）买家/button_u27_mouseOver.png"}}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u1.png"}},
{
            "id":"901bf5fad6b24aa28879e999b676ff29",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF99CCFF},
              "location":{
                "x":65,
                "y":120},
              "size":{
                "width":322,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d3c8f6ba4db54b7180dda95fdac9eb33",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF99CCFF},
                  "location":{
                    "x":65,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u11.png"}},
{
            "id":"3ae9b2d30d6c4e47974da0f1f40183cb",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":335,
                "y":123},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"238713c20ad94bb7beb171261a931644",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":335,
                    "y":123},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}},
{
            "id":"3245d7b29b184ae8bb4282155a41dc68",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":311,
                "y":122},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2483113f29fe4494a91ab6354144197f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":311,
                    "y":122},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u15.png"}},
{
            "id":"29b6cbaf58714338a233837b0fc50538",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":289,
                "y":122},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d12b80914ce141e881fc147bcdba67d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":289,
                    "y":122},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u17.png"}},
{
            "id":"df8c8bfcfb7248908696b24c74cdebc7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":359,
                "y":123},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"492530becc094a6f88000e4ef95c81b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":359,
                    "y":123},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u19.png"}}]}}},
  "objectPaths":{
    "4d0975820f4243d3aba87a5ac568c933":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "901bf5fad6b24aa28879e999b676ff29":{
        "scriptId":"u3"},
      "d3c8f6ba4db54b7180dda95fdac9eb33":{
        "scriptId":"u4"},
      "3ae9b2d30d6c4e47974da0f1f40183cb":{
        "scriptId":"u5"},
      "238713c20ad94bb7beb171261a931644":{
        "scriptId":"u6"},
      "3245d7b29b184ae8bb4282155a41dc68":{
        "scriptId":"u7"},
      "2483113f29fe4494a91ab6354144197f":{
        "scriptId":"u8"},
      "29b6cbaf58714338a233837b0fc50538":{
        "scriptId":"u9"},
      "d12b80914ce141e881fc147bcdba67d8":{
        "scriptId":"u10"},
      "df8c8bfcfb7248908696b24c74cdebc7":{
        "scriptId":"u11"},
      "492530becc094a6f88000e4ef95c81b1":{
        "scriptId":"u12"}},
    "9b1c42a66edf4a6abb033a6118044ec5":{
      "scriptId":"u13"},
    "f023fba5f3b64e13922492205ad5c387":{
      "scriptId":"u14"},
    "4b62b9f0c1b14892a1f82fc173c88241":{
      "scriptId":"u15"},
    "ab25497c5eba45578608d200073e7deb":{
      "scriptId":"u16"},
    "83e51bf44a3f47258e2cf3af1beb2ac3":{
      "scriptId":"u17"},
    "fcf8b44272264b079ce86ee25bed0339":{
      "scriptId":"u18"},
    "ee05022fe1c44eeaac439912b3063633":{
      "scriptId":"u19"},
    "5f7afe965bcd47cc9e132d1a1e01aa6f":{
      "scriptId":"u20"},
    "9f9ab6f8df334d6ab522ec253e1c9881":{
      "scriptId":"u21"},
    "d1336718b54e49f2b4a444fed339e599":{
      "scriptId":"u22"},
    "6d535a454f0f4b809d968fd959e89496":{
      "scriptId":"u23"},
    "1494d8ee452a4642bba70ec31d63a6a7":{
      "scriptId":"u24"},
    "bb1773f3c5304dc0be10d77dad8b56d2":{
      "scriptId":"u25"},
    "105e650cecd8419292b3ac41479ad240":{
      "scriptId":"u26"},
    "2857b2e5607946c3979f85e67c277e60":{
      "scriptId":"u27"},
    "83143ed265444f75aef6982f420282f6":{
      "scriptId":"u28"}}});