$axure.loadCurrentPage({
  "url":"已发布的订单.html",
  "generationDate":new Date(1408680670460.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba2a8839d21e4feb838cb4b05d0e1761",
    "type":"Axure:Page",
    "name":"已发布的订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3407557574aa40e08cc31253bc8274aa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"ccb73e57667f4e0b8e6cd4a5914c8eea",
          "label":"已发布订单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":179},
            "size":{
              "width":321,
              "height":418}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d7f7f6fc8e984d7fb024151acff92f17",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8dd1e1178e6c4c00bbf26661c6b338d9",
                  "label":"Link",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":300,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ee87a0e9ca04e73a8a149163df7cd43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":300,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单详细（买家）",
                              "target":{
                                "targetType":"page",
                                "url":"订单详细（买家）.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"740be7169b2d48fb9d31af7db0c90fd4",
                  "label":"买手接单",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":224,
                      "y":19},
                    "size":{
                      "width":75,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1064e5d5313415fbb7f9673b7077e8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":224,
                          "y":19},
                        "size":{
                          "width":75,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/买家确认_u8.png"}},
{
                  "id":"af9ed8c67b30435b840b9be072fee490",
                  "label":"Link",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":300,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9de231efae6049adbb946d140e06cafa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":76},
                        "size":{
                          "width":300,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If 部件文字 买手确认 = &quot;买手确认中&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["f317eee50900471b867049f8fcb69389"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"买手确认中",
                              "stos":[]}},
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单详细（开始购买）买家",
                              "target":{
                                "targetType":"page",
                                "url":"订单详细（开始购买）买家.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f317eee50900471b867049f8fcb69389",
                  "label":"买手确认",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":220,
                      "y":95},
                    "size":{
                      "width":79,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d43357bdf89143a8b6209a1ee0c44b49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":220,
                          "y":95},
                        "size":{
                          "width":79,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/买家付款_u12.png"}},
{
                  "id":"22b485ce532041fbb5cfbb9a69fc2efc",
                  "label":"Link",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":155},
                    "size":{
                      "width":299,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8329f274965b4b6a855b9d304c9630d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":155},
                        "size":{
                          "width":299,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If 部件文字 寻求买手 = &quot;寻求买手中&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["b8c2bcf597014835b8c21fca6691bd31"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"寻求买手中",
                              "stos":[]}},
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单详细（复制）",
                              "target":{
                                "targetType":"page",
                                "url":"订单详细（复制）.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"b8c2bcf597014835b8c21fca6691bd31",
                  "label":"寻求买手",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":220,
                      "y":174},
                    "size":{
                      "width":78,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e45065381a674ba0ab47d399d89ed482",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":220,
                          "y":174},
                        "size":{
                          "width":78,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/购买中_u16.png"}},
{
                  "id":"35b561cc06f8492db8b2282e3c3281f8",
                  "label":"Link",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":-2,
                      "y":236},
                    "size":{
                      "width":301,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfb84f5ef9e24a1a811cbe940f9e9756",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":-2,
                          "y":236},
                        "size":{
                          "width":301,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"b751e8b5b6c34c45a1ece347942705f3",
                  "label":"Rectangle",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":219,
                      "y":261},
                    "size":{
                      "width":79,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31b237e736974d369c6e12e13180b83b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":219,
                          "y":261},
                        "size":{
                          "width":79,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/买家付款_u12.png"}},
{
                  "id":"90373f989d334a2683518ae3e3404345",
                  "label":"Link",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":-2,
                      "y":316},
                    "size":{
                      "width":300,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ee355d3f69d4017b609d36cd3a1b61c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":-2,
                          "y":316},
                        "size":{
                          "width":300,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"efd19f0f48ba4c34b2fb3a72ed9fbb56",
                  "label":"Rectangle",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":218,
                      "y":335},
                    "size":{
                      "width":79,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"faa584c19f854ce3b018401f10627b04",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":218,
                          "y":335},
                        "size":{
                          "width":79,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/买家付款_u12.png"}},
{
                  "id":"678d878a43bf43ef8fefd0e498c6f241",
                  "label":"",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":69},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的代购订单/u26_line.png"}},
{
                  "id":"749d1d8550d8430099c160ca8e3ae036",
                  "label":"",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":145},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的代购订单/u26_line.png"}},
{
                  "id":"dc4b73fc048049898af899d0b6c9d45f",
                  "label":"",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":224},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的代购订单/u26_line.png"}},
{
                  "id":"1509f4d17ea44fc391de7a4d6afe6513",
                  "label":"",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":305},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的代购订单/u26_line.png"}},
{
                  "id":"589846a290fe499e847b2dba0e4ca013",
                  "label":"Link",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":394},
                    "size":{
                      "width":297,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"947c72f231774ef0ad50fd8080dc6b63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":394},
                        "size":{
                          "width":297,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"1bbd1230cea44b06b8778d8ac561e6ad",
                  "label":"Rectangle",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":218,
                      "y":413},
                    "size":{
                      "width":78,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebf39a819aa545b6bfbfdfe6c8d6703f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":218,
                          "y":413},
                        "size":{
                          "width":78,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/购买中_u16.png"}},
{
                  "id":"5dfbb79a1fa3424ba392a3bde792e23e",
                  "label":"",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":385},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的代购订单/u26_line.png"}},
{
                  "id":"e878e023b529493789c18481757044e3",
                  "label":"Loading Large",
                  "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":143,
                      "y":467},
                    "size":{
                      "width":32,
                      "height":32},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"507a97f3cf6a48a9a3a857573f44dbd6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ccb73e57667f4e0b8e6cd4a5914c8eea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":143,
                          "y":467},
                        "size":{
                          "width":32,
                          "height":32},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的代购订单/loading_large_u35.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"49bdead7de6c4d17a005be2e3150462b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "3407557574aa40e08cc31253bc8274aa":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "ccb73e57667f4e0b8e6cd4a5914c8eea":{
      "scriptId":"u5"},
    "8dd1e1178e6c4c00bbf26661c6b338d9":{
      "scriptId":"u6"},
    "6ee87a0e9ca04e73a8a149163df7cd43":{
      "scriptId":"u7"},
    "740be7169b2d48fb9d31af7db0c90fd4":{
      "scriptId":"u8"},
    "e1064e5d5313415fbb7f9673b7077e8f":{
      "scriptId":"u9"},
    "af9ed8c67b30435b840b9be072fee490":{
      "scriptId":"u10"},
    "9de231efae6049adbb946d140e06cafa":{
      "scriptId":"u11"},
    "f317eee50900471b867049f8fcb69389":{
      "scriptId":"u12"},
    "d43357bdf89143a8b6209a1ee0c44b49":{
      "scriptId":"u13"},
    "22b485ce532041fbb5cfbb9a69fc2efc":{
      "scriptId":"u14"},
    "8329f274965b4b6a855b9d304c9630d8":{
      "scriptId":"u15"},
    "b8c2bcf597014835b8c21fca6691bd31":{
      "scriptId":"u16"},
    "e45065381a674ba0ab47d399d89ed482":{
      "scriptId":"u17"},
    "35b561cc06f8492db8b2282e3c3281f8":{
      "scriptId":"u18"},
    "dfb84f5ef9e24a1a811cbe940f9e9756":{
      "scriptId":"u19"},
    "b751e8b5b6c34c45a1ece347942705f3":{
      "scriptId":"u20"},
    "31b237e736974d369c6e12e13180b83b":{
      "scriptId":"u21"},
    "90373f989d334a2683518ae3e3404345":{
      "scriptId":"u22"},
    "6ee355d3f69d4017b609d36cd3a1b61c":{
      "scriptId":"u23"},
    "efd19f0f48ba4c34b2fb3a72ed9fbb56":{
      "scriptId":"u24"},
    "faa584c19f854ce3b018401f10627b04":{
      "scriptId":"u25"},
    "678d878a43bf43ef8fefd0e498c6f241":{
      "scriptId":"u26"},
    "749d1d8550d8430099c160ca8e3ae036":{
      "scriptId":"u27"},
    "dc4b73fc048049898af899d0b6c9d45f":{
      "scriptId":"u28"},
    "1509f4d17ea44fc391de7a4d6afe6513":{
      "scriptId":"u29"},
    "589846a290fe499e847b2dba0e4ca013":{
      "scriptId":"u30"},
    "947c72f231774ef0ad50fd8080dc6b63":{
      "scriptId":"u31"},
    "1bbd1230cea44b06b8778d8ac561e6ad":{
      "scriptId":"u32"},
    "ebf39a819aa545b6bfbfdfe6c8d6703f":{
      "scriptId":"u33"},
    "5dfbb79a1fa3424ba392a3bde792e23e":{
      "scriptId":"u34"},
    "e878e023b529493789c18481757044e3":{
      "scriptId":"u35"},
    "507a97f3cf6a48a9a3a857573f44dbd6":{
      "scriptId":"u36"},
    "49bdead7de6c4d17a005be2e3150462b":{
      "scriptId":"u37",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u38"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u39"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u40"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u41"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u42"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u43"}}}});