$axure.loadCurrentPage({
  "url":"订单详细（开始购买1）买手.html",
  "generationDate":new Date(1408680674158.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d20a14307fc145e297fc607e72a281bd",
    "type":"Axure:Page",
    "name":"订单详细（开始购买1）买手",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88a4cbc0ff0f4060bfc1a99cc9476c51",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"92456c92f9f14580a2f2f7f0cb33caec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":66,
              "y":179},
            "size":{
              "width":320,
              "height":424}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5248ad8abc499fa0125bea3819a652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":66,
                  "y":179},
                "size":{
                  "width":320,
                  "height":424}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（开始购买1）买手/u5.png"}},
{
          "id":"99b176c49bf44d159384ba27d688e96d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":68,
              "y":194},
            "size":{
              "width":115,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19800f92604f4a1d97528a2ac0bb5685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":68,
                  "y":194},
                "size":{
                  "width":115,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（复制）/u10.png"}},
{
          "id":"b5f958cd5b9d41a994e6e0ecf665b659",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":249,
              "y":553},
            "size":{
              "width":110,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e52b4b7618874a6280e7579ee0ac0b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":249,
                  "y":553},
                "size":{
                  "width":110,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详细（购买完成）买手",
                      "target":{
                        "targetType":"page",
                        "url":"订单详细（购买完成）买手.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单详细（新建1）买手/button_u9.png",
            "mouseOver~":"images/订单详细（新建1）买手/button_u9_mouseOver.png"}},
{
          "id":"57da857cbb6049eea041924668e61c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":184,
              "y":192},
            "size":{
              "width":203,
              "height":137},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1298d2472443b4af2d37e50207954e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":184,
                  "y":192},
                "size":{
                  "width":203,
                  "height":137},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（发货）/u9.png"}},
{
          "id":"fa10f361c1694bf7bf56ad2f2cfb5660",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":66,
              "y":329},
            "size":{
              "width":320,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131f7649e2834da39bcabb145fbd77c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":66,
                  "y":329},
                "size":{
                  "width":320,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（开始购买1）买手/u13.png"}},
{
          "id":"063e41ffee104fe4b989781c5c46df33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":66,
              "y":508},
            "size":{
              "width":319,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea7ce7174ec49749e8499944ada7943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":66,
                  "y":508},
                "size":{
                  "width":319,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（开始购买1）买手/u15.png"}},
{
          "id":"84df6d6f5be146889e29aac485582b18",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":68,
              "y":544},
            "size":{
              "width":164,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2f58a9ec4ad441082d059cf8e868ba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":68,
                  "y":544},
                "size":{
                  "width":164,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（开始购买1）买手/u17.png"}},
{
          "id":"5ffd8d538a4048dd88233a876e74a313",
          "label":"Tab",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":67,
              "y":453},
            "size":{
              "width":66,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0417d02c5f1d4380afb671d933294f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":67,
                  "y":453},
                "size":{
                  "width":66,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（发货）/tab_u17.png"}},
{
          "id":"3d8df0c47304400bbbb04ed2d9dffaaa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":67,
              "y":477},
            "size":{
              "width":320,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6452f0663f024572a58bd640453325ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":67,
                  "y":477},
                "size":{
                  "width":320,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新建私信",
                      "target":{
                        "targetType":"page",
                        "url":"新建私信.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单详细（发货）/u19.png"}},
{
          "id":"e6eb308ff2c74a3b81ce7b3aaccf095a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "88a4cbc0ff0f4060bfc1a99cc9476c51":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "92456c92f9f14580a2f2f7f0cb33caec":{
      "scriptId":"u5"},
    "fe5248ad8abc499fa0125bea3819a652":{
      "scriptId":"u6"},
    "99b176c49bf44d159384ba27d688e96d":{
      "scriptId":"u7"},
    "19800f92604f4a1d97528a2ac0bb5685":{
      "scriptId":"u8"},
    "b5f958cd5b9d41a994e6e0ecf665b659":{
      "scriptId":"u9"},
    "e52b4b7618874a6280e7579ee0ac0b40":{
      "scriptId":"u10"},
    "57da857cbb6049eea041924668e61c95":{
      "scriptId":"u11"},
    "9d1298d2472443b4af2d37e50207954e":{
      "scriptId":"u12"},
    "fa10f361c1694bf7bf56ad2f2cfb5660":{
      "scriptId":"u13"},
    "131f7649e2834da39bcabb145fbd77c4":{
      "scriptId":"u14"},
    "063e41ffee104fe4b989781c5c46df33":{
      "scriptId":"u15"},
    "dea7ce7174ec49749e8499944ada7943":{
      "scriptId":"u16"},
    "84df6d6f5be146889e29aac485582b18":{
      "scriptId":"u17"},
    "f2f58a9ec4ad441082d059cf8e868ba4":{
      "scriptId":"u18"},
    "5ffd8d538a4048dd88233a876e74a313":{
      "scriptId":"u19"},
    "0417d02c5f1d4380afb671d933294f19":{
      "scriptId":"u20"},
    "3d8df0c47304400bbbb04ed2d9dffaaa":{
      "scriptId":"u21"},
    "6452f0663f024572a58bd640453325ca":{
      "scriptId":"u22"},
    "e6eb308ff2c74a3b81ce7b3aaccf095a":{
      "scriptId":"u23",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u24"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u25"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u26"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u27"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u28"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u29"}}}});