$axure.loadCurrentPage({
  "url":"清单一览.html",
  "generationDate":new Date(1408680670105.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5341a2e7e1e7459b96a362688e7e9148",
    "type":"Axure:Page",
    "name":"清单一览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"918febe5162140eda57a2b08930348c9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5e0f6785936c4012b80ddc166e0c4560"},
{
          "id":"5089010c90d647918e3069fe6c2f0beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":65,
              "y":179},
            "size":{
              "width":322,
              "height":391}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6cab33dcdf1476a935fa06bd6bd47b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":65,
                  "y":179},
                "size":{
                  "width":322,
                  "height":391}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u15.png"}},
{
          "id":"e47a197a2d4245899f019c142436d647",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":65,
              "y":200},
            "size":{
              "width":322,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"486a32eca29f4f1e87ddfde903b97a12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":65,
                  "y":200},
                "size":{
                  "width":322,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详细（买手）",
                      "target":{
                        "targetType":"page",
                        "url":"订单详细（买手）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/清单一览/u17.png"}},
{
          "id":"a8f40208f8344784942dd49079ecbf90",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0de6210566dd4614a4f81872b4896af2"},
{
          "id":"3a39339698904c3f9aa83805982dc8a9",
          "label":"Dropdown Menu",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":325,
              "y":149},
            "size":{
              "width":55,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"8fb22f8a9357431e9ee4b18366a46937",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":65,
              "y":264},
            "size":{
              "width":322,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74329edf51e0483281deaa868b82a012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":65,
                  "y":264},
                "size":{
                  "width":322,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u17.png"}},
{
          "id":"343bcea2025947058351217ae96d2697",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":66,
              "y":329},
            "size":{
              "width":322,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b820c7a7d2a4127bbed211e5408f73e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":66,
                  "y":329},
                "size":{
                  "width":322,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u17.png"}},
{
          "id":"85be40e6581f4643a2b233b32d8ddfa7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":66,
              "y":393},
            "size":{
              "width":322,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f20205a396494dc5aa5ad40482777a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":66,
                  "y":393},
                "size":{
                  "width":322,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/清单一览/u17.png"}}]}},
  "masters":{
    "5e0f6785936c4012b80ddc166e0c4560":{
      "packageId":"5e0f6785936c4012b80ddc166e0c4560",
      "type":"Axure:Master",
      "name":"手机带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1b205b6aeef2413b88e1d633ea7511d6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":64,
                "y":570},
              "size":{
                "width":322,
                "height":30},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53e62992bfdb47b683c106941fc81ec0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":64,
                    "y":570},
                  "size":{
                    "width":322,
                    "height":30},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u1.png"}},
{
            "id":"f6006b5d5baa46999c7cf32d94d6f166",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c3ab424966d246fdb5e45eb4afcdf778",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"376607bd7c274dafa220f6c087c4779c",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":66,
                "y":570},
              "size":{
                "width":80,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"660425e3d91c4ea2b44248e29d14fed2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":66,
                    "y":570},
                  "size":{
                    "width":80,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["376607bd7c274dafa220f6c087c4779c"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn1_u5.png",
              "selected~":"images/主页/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/主页/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ef426acdd5884c2580d1f8fecc379796",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":305,
                "y":570},
              "size":{
                "width":81,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9dbd829d9824183a1338cbe3aa031b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":305,
                    "y":570},
                  "size":{
                    "width":81,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ef426acdd5884c2580d1f8fecc379796"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的（登录后）",
                        "target":{
                          "targetType":"page",
                          "url":"我的（登录后）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn4_u7.png",
              "selected~":"images/主页/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/主页/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"80012608a8d44d698ecac65c8e170cbf",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":145,
                "y":570},
              "size":{
                "width":81,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee8f8c5e6ca346bdba5725c2383f372b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":145,
                    "y":570},
                  "size":{
                    "width":81,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["80012608a8d44d698ecac65c8e170cbf"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 清单一览",
                        "target":{
                          "targetType":"page",
                          "url":"清单一览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn4_u7.png",
              "selected~":"images/主页/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/主页/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"a51c84b091884f8bb0b2d6b764e32be6",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":226,
                "y":570},
              "size":{
                "width":80,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b483f339b018443094743646a184d0a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":226,
                    "y":570},
                  "size":{
                    "width":80,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["a51c84b091884f8bb0b2d6b764e32be6"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的订单一览",
                        "target":{
                          "targetType":"page",
                          "url":"我的订单一览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn1_u5.png",
              "selected~":"images/主页/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/主页/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ec15bb5d8bd049209662ccb717cc1a52",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":66,
                "y":120},
              "size":{
                "width":320,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7b6262ff7f0444988f65a72dc522603",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":66,
                    "y":120},
                  "size":{
                    "width":320,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "0de6210566dd4614a4f81872b4896af2":{
      "packageId":"0de6210566dd4614a4f81872b4896af2",
      "type":"Axure:Master",
      "name":"头部一级",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":78,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":78,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"4bd8bc1c9de9428c9013ab06e59631c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h4",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "location":{
                "x":108,
                "y":146},
              "size":{
                "width":72,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"afa01676eda8434c8bc3894106940c4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":108,
                    "y":146},
                  "size":{
                    "width":72,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "918febe5162140eda57a2b08930348c9":{
      "scriptId":"u0",
      "1b205b6aeef2413b88e1d633ea7511d6":{
        "scriptId":"u1"},
      "53e62992bfdb47b683c106941fc81ec0":{
        "scriptId":"u2"},
      "f6006b5d5baa46999c7cf32d94d6f166":{
        "scriptId":"u3"},
      "c3ab424966d246fdb5e45eb4afcdf778":{
        "scriptId":"u4"},
      "376607bd7c274dafa220f6c087c4779c":{
        "scriptId":"u5"},
      "660425e3d91c4ea2b44248e29d14fed2":{
        "scriptId":"u6"},
      "ef426acdd5884c2580d1f8fecc379796":{
        "scriptId":"u7"},
      "b9dbd829d9824183a1338cbe3aa031b7":{
        "scriptId":"u8"},
      "80012608a8d44d698ecac65c8e170cbf":{
        "scriptId":"u9"},
      "ee8f8c5e6ca346bdba5725c2383f372b":{
        "scriptId":"u10"},
      "a51c84b091884f8bb0b2d6b764e32be6":{
        "scriptId":"u11"},
      "b483f339b018443094743646a184d0a7":{
        "scriptId":"u12"},
      "ec15bb5d8bd049209662ccb717cc1a52":{
        "scriptId":"u13"},
      "c7b6262ff7f0444988f65a72dc522603":{
        "scriptId":"u14"}},
    "5089010c90d647918e3069fe6c2f0beb":{
      "scriptId":"u15"},
    "b6cab33dcdf1476a935fa06bd6bd47b8":{
      "scriptId":"u16"},
    "e47a197a2d4245899f019c142436d647":{
      "scriptId":"u17"},
    "486a32eca29f4f1e87ddfde903b97a12":{
      "scriptId":"u18"},
    "a8f40208f8344784942dd49079ecbf90":{
      "scriptId":"u19",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u20"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u21"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u22"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u23"},
      "4bd8bc1c9de9428c9013ab06e59631c4":{
        "scriptId":"u24"},
      "afa01676eda8434c8bc3894106940c4e":{
        "scriptId":"u25"}},
    "3a39339698904c3f9aa83805982dc8a9":{
      "scriptId":"u26"},
    "8fb22f8a9357431e9ee4b18366a46937":{
      "scriptId":"u27"},
    "74329edf51e0483281deaa868b82a012":{
      "scriptId":"u28"},
    "343bcea2025947058351217ae96d2697":{
      "scriptId":"u29"},
    "7b820c7a7d2a4127bbed211e5408f73e":{
      "scriptId":"u30"},
    "85be40e6581f4643a2b233b32d8ddfa7":{
      "scriptId":"u31"},
    "f20205a396494dc5aa5ad40482777a95":{
      "scriptId":"u32"}}});