$axure.loadCurrentPage({
  "url":"买手详细列表.html",
  "generationDate":new Date(1408595826867.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"781a999539ef4565a452c298e29b9b2b",
    "type":"Axure:Page",
    "name":"买手详细列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bcee2e2992e048138784f5484daa0ab9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":84,
              "y":155},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4799c20247af4c4db8e20b898fbb7b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":84,
                  "y":155},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u21.png"}},
{
          "id":"514ce73282fc48439b8dda102fa60b3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":78,
              "y":156},
            "size":{
              "width":33,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14670d1a90524388a009b62fbc593a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":78,
                  "y":156},
                "size":{
                  "width":33,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的预购订单/u15.png"}},
{
          "id":"e38142d3f81d43d7a1fddc9889cb52e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":111,
              "y":160},
            "size":{
              "width":28,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1be340bbee1641dbb73e7d6a1ffc4da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":111,
                  "y":160},
                "size":{
                  "width":28,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9f6ff1d99924a59875858debef392bb",
          "label":"买手详细",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":195},
            "size":{
              "width":315,
              "height":415}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"550e71e3044543dab95e4acd203f8cf4",
              "label":"列表",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8a932f890bce4c849381ee6bc07ac174",
                  "label":"",
                  "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                  "panelIndex":0,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"left",
                    "location":{
                      "x":1,
                      "y":1},
                    "size":{
                      "width":313,
                      "height":107},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f480e9bad314343896b6e4e8103b860",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"left",
                        "location":{
                          "x":1,
                          "y":1},
                        "size":{
                          "width":313,
                          "height":107},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单详细（购买）买家",
                              "target":{
                                "targetType":"page",
                                "url":"订单详细（购买）买家.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/买手详细列表/u7.png"}},
{
                  "id":"3f4f8ad7651b4df69083ae83a6cccf47",
                  "label":"",
                  "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                  "panelIndex":0,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4}]},
                    "location":{
                      "x":0,
                      "y":108},
                    "size":{
                      "width":313,
                      "height":107},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b5fe2fe24a34bdc80a4b412e6cda369",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFC9C9C9},
{
                              "color":0xFFC9C9C9},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":313,
                          "height":107},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买手详细列表/u9.png"}},
{
                  "id":"c46a46e172b24287ba7ea1a7cc78a8b2",
                  "label":"",
                  "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                  "panelIndex":0,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"left",
                    "location":{
                      "x":1,
                      "y":214},
                    "size":{
                      "width":313,
                      "height":107},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39d7c97715e84e54aae825a9b9b0fb55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"left",
                        "location":{
                          "x":1,
                          "y":214},
                        "size":{
                          "width":313,
                          "height":107},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买手详细列表/u7.png"}},
{
                  "id":"c9cfea99d4664e558ac6a9a33184f0ac",
                  "label":"",
                  "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                  "panelIndex":0,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"left",
                    "location":{
                      "x":2,
                      "y":437},
                    "size":{
                      "width":313,
                      "height":117},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62cf64c1ee0442e083b5f7cf55c73946",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"left",
                        "location":{
                          "x":2,
                          "y":437},
                        "size":{
                          "width":313,
                          "height":117},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买手详细列表/u13.png"}},
{
                  "id":"ad6b18b91f3f415b96cde633b3373084",
                  "label":"",
                  "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                  "panelIndex":0,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4}]},
                    "location":{
                      "x":2,
                      "y":320},
                    "size":{
                      "width":313,
                      "height":117},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01f014f1623a47aca5a136f2b8cffe69",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFC9C9C9},
{
                              "color":0xFFC9C9C9},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]},
                        "location":{
                          "x":2,
                          "y":320},
                        "size":{
                          "width":313,
                          "height":117},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买手详细列表/u15.png"}},
{
                  "id":"b67677e69152453b9d0af2c0f384d0a4",
                  "label":"Loading Large",
                  "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":130,
                      "y":566},
                    "size":{
                      "width":32,
                      "height":32},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"419959e904384eca96c150f4e833db72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9f6ff1d99924a59875858debef392bb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":130,
                          "y":566},
                        "size":{
                          "width":32,
                          "height":32},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的预购订单/loading_large_u41.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "bcee2e2992e048138784f5484daa0ab9":{
      "scriptId":"u0"},
    "4799c20247af4c4db8e20b898fbb7b36":{
      "scriptId":"u1"},
    "514ce73282fc48439b8dda102fa60b3e":{
      "scriptId":"u2"},
    "14670d1a90524388a009b62fbc593a01":{
      "scriptId":"u3"},
    "e38142d3f81d43d7a1fddc9889cb52e7":{
      "scriptId":"u4"},
    "1be340bbee1641dbb73e7d6a1ffc4da7":{
      "scriptId":"u5"},
    "f9f6ff1d99924a59875858debef392bb":{
      "scriptId":"u6"},
    "8a932f890bce4c849381ee6bc07ac174":{
      "scriptId":"u7"},
    "7f480e9bad314343896b6e4e8103b860":{
      "scriptId":"u8"},
    "3f4f8ad7651b4df69083ae83a6cccf47":{
      "scriptId":"u9"},
    "2b5fe2fe24a34bdc80a4b412e6cda369":{
      "scriptId":"u10"},
    "c46a46e172b24287ba7ea1a7cc78a8b2":{
      "scriptId":"u11"},
    "39d7c97715e84e54aae825a9b9b0fb55":{
      "scriptId":"u12"},
    "c9cfea99d4664e558ac6a9a33184f0ac":{
      "scriptId":"u13"},
    "62cf64c1ee0442e083b5f7cf55c73946":{
      "scriptId":"u14"},
    "ad6b18b91f3f415b96cde633b3373084":{
      "scriptId":"u15"},
    "01f014f1623a47aca5a136f2b8cffe69":{
      "scriptId":"u16"},
    "b67677e69152453b9d0af2c0f384d0a4":{
      "scriptId":"u17"},
    "419959e904384eca96c150f4e833db72":{
      "scriptId":"u18"}}});