$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1408680670984.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d682b28d61f6438c9ee7b77ec3c697c4",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b4e10d6a5924f9994f98ea580d46b2b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"3f5bc01b73e94c24988b8af089f62b5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":66,
              "y":179},
            "size":{
              "width":323,
              "height":418}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a58a7516c2f4828bda7b1411157cc62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":66,
                  "y":179},
                "size":{
                  "width":323,
                  "height":418}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u5.png"}},
{
          "id":"340db0ec5ea045db91e61613f84f9d8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":111,
              "y":197},
            "size":{
              "width":78,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03a6c1e1974246fcb3e6746caebbbbe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":111,
                  "y":197},
                "size":{
                  "width":78,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的（登录后）/u53.png"}},
{
          "id":"20ef07bac61c4a5db2b583d432c0c354",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":202,
              "y":215},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92fb8d136d8448d78507efd178a903f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":202,
                  "y":215},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e80959731a644328bcbf1e96e7662b87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":297},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a1804ba4ba8459d8a32dfd09ba15fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":297},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c146eeebefff43ae87407254be9db3b6",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":158,
              "y":293},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 密码 = &quot;请输入新密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["c146eeebefff43ae87407254be9db3b6"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"请输入新密码",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 密码 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c146eeebefff43ae87407254be9db3b6"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 密码 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["c146eeebefff43ae87407254be9db3b6"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 密码 = &quot;请输入新密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c146eeebefff43ae87407254be9db3b6"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入新密码",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"c8f0b186903f4dd5a8637f6cd52f5028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":332},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d39332ca76149abb5446a29f467c25e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":332},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95a6888a0ceb4160b5407f33e7c36d73",
          "label":"确认密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":158,
              "y":328},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 确认密码 = &quot;请输入确认新密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["95a6888a0ceb4160b5407f33e7c36d73"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"请输入确认新密码",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 确认密码 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["95a6888a0ceb4160b5407f33e7c36d73"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 确认密码 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["95a6888a0ceb4160b5407f33e7c36d73"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 确认密码 = &quot;请输入确认新密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["95a6888a0ceb4160b5407f33e7c36d73"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入确认新密码",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"c2688c52145b47a18633ad7b00453b8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":438},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e65da9455baf4637a88697e1039189cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":438},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b0931986bfe4fa4afe5d0bf9f4ea26b",
          "label":"城市",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":157,
              "y":431},
            "size":{
              "width":71,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"951d4713fb89479d8c4d95f10f140f99",
          "label":"区",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":238,
              "y":431},
            "size":{
              "width":71,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"83b06b30ecda43e89a0ddd3429a8d64b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":376},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af86e9476ea1480fa1823f07ea4469f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":376},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42bf69f1b59242a091d54492b6e1342d",
          "label":"确认密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":158,
              "y":372},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 确认密码 = &quot;请输入确认新密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["42bf69f1b59242a091d54492b6e1342d"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"请输入确认新密码",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 确认密码 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["42bf69f1b59242a091d54492b6e1342d"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 确认密码 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["42bf69f1b59242a091d54492b6e1342d"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 确认密码 = &quot;请输入确认新密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["42bf69f1b59242a091d54492b6e1342d"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入确认新密码",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"154b0a45028a42acbba6d71ee8ccac8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":374},
            "size":{
              "width":27,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243b45a05b254fc595d6a9ad994abdfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":374},
                "size":{
                  "width":27,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 出生年月",
                      "objectsToFades":[{
                          "objectPath":["3122428fd6da40c890bc253e79cc2a54"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/u24.png"}},
{
          "id":"3122428fd6da40c890bc253e79cc2a54",
          "label":"出生年月",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":281,
              "y":397},
            "size":{
              "width":130,
              "height":110},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"521586c483aa413abf4e3a25dfc7e9c5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bb52e536704e4b01a39ceefb1472df29",
                  "label":"",
                  "parentDynamicPanel":"3122428fd6da40c890bc253e79cc2a54",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":130,
                      "height":110}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb4d90b7c62f4ad9a95f261794eebb17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3122428fd6da40c890bc253e79cc2a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":130,
                          "height":110}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置/u27.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"18cc5fb757ab449ca571ab3041b619ce",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"},
{
          "id":"782453ae17e24023ba692685406ec54d",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":315,
              "y":147},
            "size":{
              "width":70,
              "height":29},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c42c02a4866f4de1b9d1cdddb68dfbe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":315,
                  "y":147},
                "size":{
                  "width":70,
                  "height":29},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的（登录后）",
                      "target":{
                        "targetType":"page",
                        "url":"我的（登录后）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/button_u36.png",
            "mouseOver~":"images/设置/button_u36_mouseOver.png"}}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "6b4e10d6a5924f9994f98ea580d46b2b":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "3f5bc01b73e94c24988b8af089f62b5a":{
      "scriptId":"u5"},
    "7a58a7516c2f4828bda7b1411157cc62":{
      "scriptId":"u6"},
    "340db0ec5ea045db91e61613f84f9d8f":{
      "scriptId":"u7"},
    "03a6c1e1974246fcb3e6746caebbbbe3":{
      "scriptId":"u8"},
    "20ef07bac61c4a5db2b583d432c0c354":{
      "scriptId":"u9"},
    "92fb8d136d8448d78507efd178a903f5":{
      "scriptId":"u10"},
    "e80959731a644328bcbf1e96e7662b87":{
      "scriptId":"u11"},
    "4a1804ba4ba8459d8a32dfd09ba15fc4":{
      "scriptId":"u12"},
    "c146eeebefff43ae87407254be9db3b6":{
      "scriptId":"u13"},
    "c8f0b186903f4dd5a8637f6cd52f5028":{
      "scriptId":"u14"},
    "4d39332ca76149abb5446a29f467c25e":{
      "scriptId":"u15"},
    "95a6888a0ceb4160b5407f33e7c36d73":{
      "scriptId":"u16"},
    "c2688c52145b47a18633ad7b00453b8b":{
      "scriptId":"u17"},
    "e65da9455baf4637a88697e1039189cb":{
      "scriptId":"u18"},
    "9b0931986bfe4fa4afe5d0bf9f4ea26b":{
      "scriptId":"u19"},
    "951d4713fb89479d8c4d95f10f140f99":{
      "scriptId":"u20"},
    "83b06b30ecda43e89a0ddd3429a8d64b":{
      "scriptId":"u21"},
    "af86e9476ea1480fa1823f07ea4469f9":{
      "scriptId":"u22"},
    "42bf69f1b59242a091d54492b6e1342d":{
      "scriptId":"u23"},
    "154b0a45028a42acbba6d71ee8ccac8b":{
      "scriptId":"u24"},
    "243b45a05b254fc595d6a9ad994abdfa":{
      "scriptId":"u25"},
    "3122428fd6da40c890bc253e79cc2a54":{
      "scriptId":"u26"},
    "bb52e536704e4b01a39ceefb1472df29":{
      "scriptId":"u27"},
    "cb4d90b7c62f4ad9a95f261794eebb17":{
      "scriptId":"u28"},
    "18cc5fb757ab449ca571ab3041b619ce":{
      "scriptId":"u29",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u30"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u31"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u32"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u33"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u34"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u35"}},
    "782453ae17e24023ba692685406ec54d":{
      "scriptId":"u36"},
    "c42c02a4866f4de1b9d1cdddb68dfbe1":{
      "scriptId":"u37"}}});