$axure.loadCurrentPage({
  "url":"支付页面3.html",
  "generationDate":new Date(1408680673288.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ee1a924cd4794d0da1de1446e868ecf8",
    "type":"Axure:Page",
    "name":"支付页面3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd45de8cec4d4e8aa6585bd3cd9648e8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"b853781ccd9d425dae3ebe931f49caaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":66,
              "y":179},
            "size":{
              "width":320,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19444a094b3a40f8b49499fa5f6c539e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":66,
                  "y":179},
                "size":{
                  "width":320,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买手注册/u5.png"}},
{
          "id":"a0840c4bc6334a9ab7a90ac9623262c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":67,
              "y":179},
            "size":{
              "width":319,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e0d5dcc20734b6ea5c55eacd551a04b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":67,
                  "y":179},
                "size":{
                  "width":319,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u7.png"}},
{
          "id":"75df41a613484c07a2f1437d2d561bea",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":361},
            "size":{
              "width":319,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f299e12a55304a49b4187dc8e8606d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":361},
                "size":{
                  "width":319,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u9.png"}},
{
          "id":"e1e316cc136f45d58c4b57e68d3aa07d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":102,
              "y":405},
            "size":{
              "width":284,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2457fa4bbbb2442ba3cf1081e6fb2bde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":102,
                  "y":405},
                "size":{
                  "width":284,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u11.png"}},
{
          "id":"a2434c6c95cd4a21a54f0324b368b89c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":102,
              "y":438},
            "size":{
              "width":284,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de8e024117374885a5b025d43c958f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":102,
                  "y":438},
                "size":{
                  "width":284,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u11.png"}},
{
          "id":"db115626321e4a64ba2cda75e86ab097",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":102,
              "y":472},
            "size":{
              "width":284,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9942f528924b4808a16771dcdd2112d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":102,
                  "y":472},
                "size":{
                  "width":284,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u11.png"}},
{
          "id":"30fb3c9ba5ba4a599bef299dea34bf38",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":102,
              "y":505},
            "size":{
              "width":284,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8611ec97b74efc88b29fdef61e40b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":102,
                  "y":505},
                "size":{
                  "width":284,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u11.png"}},
{
          "id":"9eb55b4def154b9aa31db299a632bc17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":66,
              "y":405},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ba679744c643618509872668c51128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":66,
                  "y":405},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u19.png"}},
{
          "id":"00d5292af90840feb50b0f6e4e7ee599",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":66,
              "y":438},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e01c6b40f7244c2a13fe9202ee0b10e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":66,
                  "y":438},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u21.jpg"}},
{
          "id":"b6854832e66640a89228c3d9d8be6742",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":66,
              "y":472},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aac8eb3b45a4b8bb4128afb102ce437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":66,
                  "y":472},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u23.jpg"}},
{
          "id":"fb7a7978f3a244b3bb44e47281f3d9e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":66,
              "y":505},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9b93082ea041bd83060d09d4ea0207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":66,
                  "y":505},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面3/u25.jpg"}},
{
          "id":"5c1d91e1ad1b4c1b8472f7af77fb2685",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":361,
              "y":412},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517e4fb86b9b4f8281a5938beeec0773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":361,
                  "y":412},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 (单选框) = &quot;true&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5c1d91e1ad1b4c1b8472f7af77fb2685"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a3e68f10fa740f89abff73d9c7fd1ba"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f352127f53d8498198bd52bb1faeb0f6"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["cc4610c7b83e4a039f44c8eb3130dd88"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"7a3e68f10fa740f89abff73d9c7fd1ba",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":361,
              "y":448},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c776122867b4b89ba3dd3b6e30cbd0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":361,
                  "y":448},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;true&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5c1d91e1ad1b4c1b8472f7af77fb2685"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a3e68f10fa740f89abff73d9c7fd1ba"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f352127f53d8498198bd52bb1faeb0f6"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["cc4610c7b83e4a039f44c8eb3130dd88"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"f352127f53d8498198bd52bb1faeb0f6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":361,
              "y":513},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d03f88242e415095ef9a639acf818d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":361,
                  "y":513},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5c1d91e1ad1b4c1b8472f7af77fb2685"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a3e68f10fa740f89abff73d9c7fd1ba"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f352127f53d8498198bd52bb1faeb0f6"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["cc4610c7b83e4a039f44c8eb3130dd88"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"cc4610c7b83e4a039f44c8eb3130dd88",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":361,
              "y":481},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3b3e9ff9d8467c80118ce635a8dc16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":361,
                  "y":481},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;, 且<br> 选中状态值 (单选框) = &quot;true&quot;, 且<br> 选中状态值 (单选框) = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5c1d91e1ad1b4c1b8472f7af77fb2685"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a3e68f10fa740f89abff73d9c7fd1ba"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f352127f53d8498198bd52bb1faeb0f6"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["cc4610c7b83e4a039f44c8eb3130dd88"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"86888392693f446196e362b1a424b776",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":176,
              "y":541},
            "size":{
              "width":100,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0473fb47bf2040e08006532aa185381e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":176,
                  "y":541},
                "size":{
                  "width":100,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的（登录后）",
                      "target":{
                        "targetType":"page",
                        "url":"我的（登录后）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付页面3/button_u35.png",
            "mouseOver~":"images/支付页面3/button_u35_mouseOver.png"}},
{
          "id":"c7663758d563472cae78f3ca76fc6e64",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "bd45de8cec4d4e8aa6585bd3cd9648e8":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "b853781ccd9d425dae3ebe931f49caaa":{
      "scriptId":"u5"},
    "19444a094b3a40f8b49499fa5f6c539e":{
      "scriptId":"u6"},
    "a0840c4bc6334a9ab7a90ac9623262c6":{
      "scriptId":"u7"},
    "6e0d5dcc20734b6ea5c55eacd551a04b":{
      "scriptId":"u8"},
    "75df41a613484c07a2f1437d2d561bea":{
      "scriptId":"u9"},
    "f299e12a55304a49b4187dc8e8606d8c":{
      "scriptId":"u10"},
    "e1e316cc136f45d58c4b57e68d3aa07d":{
      "scriptId":"u11"},
    "2457fa4bbbb2442ba3cf1081e6fb2bde":{
      "scriptId":"u12"},
    "a2434c6c95cd4a21a54f0324b368b89c":{
      "scriptId":"u13"},
    "de8e024117374885a5b025d43c958f7d":{
      "scriptId":"u14"},
    "db115626321e4a64ba2cda75e86ab097":{
      "scriptId":"u15"},
    "9942f528924b4808a16771dcdd2112d3":{
      "scriptId":"u16"},
    "30fb3c9ba5ba4a599bef299dea34bf38":{
      "scriptId":"u17"},
    "eb8611ec97b74efc88b29fdef61e40b5":{
      "scriptId":"u18"},
    "9eb55b4def154b9aa31db299a632bc17":{
      "scriptId":"u19"},
    "27ba679744c643618509872668c51128":{
      "scriptId":"u20"},
    "00d5292af90840feb50b0f6e4e7ee599":{
      "scriptId":"u21"},
    "7e01c6b40f7244c2a13fe9202ee0b10e":{
      "scriptId":"u22"},
    "b6854832e66640a89228c3d9d8be6742":{
      "scriptId":"u23"},
    "2aac8eb3b45a4b8bb4128afb102ce437":{
      "scriptId":"u24"},
    "fb7a7978f3a244b3bb44e47281f3d9e5":{
      "scriptId":"u25"},
    "ca9b93082ea041bd83060d09d4ea0207":{
      "scriptId":"u26"},
    "5c1d91e1ad1b4c1b8472f7af77fb2685":{
      "scriptId":"u27"},
    "517e4fb86b9b4f8281a5938beeec0773":{
      "scriptId":"u28"},
    "7a3e68f10fa740f89abff73d9c7fd1ba":{
      "scriptId":"u29"},
    "5c776122867b4b89ba3dd3b6e30cbd0a":{
      "scriptId":"u30"},
    "f352127f53d8498198bd52bb1faeb0f6":{
      "scriptId":"u31"},
    "39d03f88242e415095ef9a639acf818d":{
      "scriptId":"u32"},
    "cc4610c7b83e4a039f44c8eb3130dd88":{
      "scriptId":"u33"},
    "2d3b3e9ff9d8467c80118ce635a8dc16":{
      "scriptId":"u34"},
    "86888392693f446196e362b1a424b776":{
      "scriptId":"u35"},
    "0473fb47bf2040e08006532aa185381e":{
      "scriptId":"u36"},
    "c7663758d563472cae78f3ca76fc6e64":{
      "scriptId":"u37",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u38"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u39"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u40"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u41"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u42"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u43"}}}});