$axure.loadCurrentPage({
  "url":"我的订单（买手）.html",
  "generationDate":new Date(1408595824899.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aefe366960e9402f947f21558caa822f",
    "type":"Axure:Page",
    "name":"我的订单（买手）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ba494b611a9f49f6ad1c9b4f5fc1b748",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"2b3663baa6bc4119b51bce737d04522d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":67,
              "y":146},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7be6fa6d4ec4ba5a25a66c6eda06daf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":67,
                  "y":146},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u21.png"}},
{
          "id":"1fc258d87b26445a8bf238952383a661",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":147},
            "size":{
              "width":33,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abdae7e490cb4868805c7c509c075d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":147},
                "size":{
                  "width":33,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的（登录后）",
                      "target":{
                        "targetType":"page",
                        "url":"我的（登录后）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的预购订单/u15.png"}},
{
          "id":"2e7cfd073b1b4386ac726db3c29b83df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":94,
              "y":151},
            "size":{
              "width":28,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47ba25f4ac524cb89e03fb33622a3a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":94,
                  "y":151},
                "size":{
                  "width":28,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc13447b9d094c56946d9486e435c1a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":66,
              "y":186},
            "size":{
              "width":323,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab763fc44104e318b44bba0f4e274b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":66,
                  "y":186},
                "size":{
                  "width":323,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u19.png"}},
{
          "id":"384076b8667a45749d70fa1a5036dd7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h4",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":188,
              "y":154},
            "size":{
              "width":75,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7b34c5aee94fd2b3b290fad4787b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":188,
                  "y":154},
                "size":{
                  "width":75,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5c22ca7254f405aa11282ee345b6ade",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":186},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5727ee424a144529f9de291a60a489f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":186},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已发布的订单",
                      "target":{
                        "targetType":"page",
                        "url":"已发布的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u29.png"}},
{
          "id":"0f147b2af704412d83dd892fd3731846",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":235},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9f1a6e21c2245688feda696e7daa89c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":235},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的预购订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的预购订单_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u29.png"}},
{
          "id":"edb303057cdc452bbf11a6c2cac5df79",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":284},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0286c45f55048a7a4c14b7c1dea70f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":284},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已完成订单",
                      "target":{
                        "targetType":"page",
                        "url":"已完成订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u29.png"}},
{
          "id":"9ed497343b9a41b3814b475cd72d331e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":344,
              "y":149},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c3718ebb923412e8f7e3bf99ca4f63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":344,
                  "y":149},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建订单",
                      "target":{
                        "targetType":"page",
                        "url":"创建订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u35.png"}},
{
          "id":"7480569067d6430799f7b1d73fdb2741",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":65,
              "y":333},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9585cfc28fcb4055948d0f8abb97d59f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":65,
                  "y":333},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的代购订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的代购订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u29.png"}}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u1.png"}},
{
            "id":"901bf5fad6b24aa28879e999b676ff29",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF99CCFF},
              "location":{
                "x":65,
                "y":120},
              "size":{
                "width":322,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d3c8f6ba4db54b7180dda95fdac9eb33",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF99CCFF},
                  "location":{
                    "x":65,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u11.png"}},
{
            "id":"3ae9b2d30d6c4e47974da0f1f40183cb",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":335,
                "y":123},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"238713c20ad94bb7beb171261a931644",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":335,
                    "y":123},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}},
{
            "id":"3245d7b29b184ae8bb4282155a41dc68",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":311,
                "y":122},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2483113f29fe4494a91ab6354144197f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":311,
                    "y":122},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u15.png"}},
{
            "id":"29b6cbaf58714338a233837b0fc50538",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":289,
                "y":122},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d12b80914ce141e881fc147bcdba67d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":289,
                    "y":122},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u17.png"}},
{
            "id":"df8c8bfcfb7248908696b24c74cdebc7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":359,
                "y":123},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"492530becc094a6f88000e4ef95c81b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":359,
                    "y":123},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u19.png"}}]}}},
  "objectPaths":{
    "ba494b611a9f49f6ad1c9b4f5fc1b748":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "901bf5fad6b24aa28879e999b676ff29":{
        "scriptId":"u3"},
      "d3c8f6ba4db54b7180dda95fdac9eb33":{
        "scriptId":"u4"},
      "3ae9b2d30d6c4e47974da0f1f40183cb":{
        "scriptId":"u5"},
      "238713c20ad94bb7beb171261a931644":{
        "scriptId":"u6"},
      "3245d7b29b184ae8bb4282155a41dc68":{
        "scriptId":"u7"},
      "2483113f29fe4494a91ab6354144197f":{
        "scriptId":"u8"},
      "29b6cbaf58714338a233837b0fc50538":{
        "scriptId":"u9"},
      "d12b80914ce141e881fc147bcdba67d8":{
        "scriptId":"u10"},
      "df8c8bfcfb7248908696b24c74cdebc7":{
        "scriptId":"u11"},
      "492530becc094a6f88000e4ef95c81b1":{
        "scriptId":"u12"}},
    "2b3663baa6bc4119b51bce737d04522d":{
      "scriptId":"u13"},
    "e7be6fa6d4ec4ba5a25a66c6eda06daf":{
      "scriptId":"u14"},
    "1fc258d87b26445a8bf238952383a661":{
      "scriptId":"u15"},
    "abdae7e490cb4868805c7c509c075d8f":{
      "scriptId":"u16"},
    "2e7cfd073b1b4386ac726db3c29b83df":{
      "scriptId":"u17"},
    "47ba25f4ac524cb89e03fb33622a3a87":{
      "scriptId":"u18"},
    "bc13447b9d094c56946d9486e435c1a3":{
      "scriptId":"u19"},
    "eab763fc44104e318b44bba0f4e274b1":{
      "scriptId":"u20"},
    "384076b8667a45749d70fa1a5036dd7f":{
      "scriptId":"u21"},
    "7b7b34c5aee94fd2b3b290fad4787b73":{
      "scriptId":"u22"},
    "b5c22ca7254f405aa11282ee345b6ade":{
      "scriptId":"u23"},
    "f5727ee424a144529f9de291a60a489f":{
      "scriptId":"u24"},
    "0f147b2af704412d83dd892fd3731846":{
      "scriptId":"u25"},
    "a9f1a6e21c2245688feda696e7daa89c":{
      "scriptId":"u26"},
    "edb303057cdc452bbf11a6c2cac5df79":{
      "scriptId":"u27"},
    "e0286c45f55048a7a4c14b7c1dea70f8":{
      "scriptId":"u28"},
    "9ed497343b9a41b3814b475cd72d331e":{
      "scriptId":"u29"},
    "0c3718ebb923412e8f7e3bf99ca4f63c":{
      "scriptId":"u30"},
    "7480569067d6430799f7b1d73fdb2741":{
      "scriptId":"u31"},
    "9585cfc28fcb4055948d0f8abb97d59f":{
      "scriptId":"u32"}}});