$axure.loadCurrentPage({
  "url":"订单详细（完成）买手.html",
  "generationDate":new Date(1408680674383.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"998a796ef3fc4be19b8c6f6165612064",
    "type":"Axure:Page",
    "name":"订单详细（完成）买手",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25d4eac930d5475dbe7600255fbab999",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"856a9923abec414f88d872acc8ab35b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":67,
              "y":179},
            "size":{
              "width":321,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7832d2d4f1dd4f3d99f6fa9df15330f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":67,
                  "y":179},
                "size":{
                  "width":321,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/服务条款/u5.png"}},
{
          "id":"475107178af84a529f3d91300a9c3ba3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":68,
              "y":191},
            "size":{
              "width":115,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19f3e05fab9140c898efc7b7b621d63a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":68,
                  "y":191},
                "size":{
                  "width":115,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（复制）/u10.png"}},
{
          "id":"aaa963c489e841528de6dc7a7c8f6a0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":184,
              "y":189},
            "size":{
              "width":203,
              "height":137},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab2589d06d5454b98f014b79e136a8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":184,
                  "y":189},
                "size":{
                  "width":203,
                  "height":137},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（发货）/u9.png"}},
{
          "id":"c77fc42f8ad1460d93b038d94ed986de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":67,
              "y":327},
            "size":{
              "width":320,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"865a97d801e24caeb03f92be2223eb59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":67,
                  "y":327},
                "size":{
                  "width":320,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（发货）/u11.png"}},
{
          "id":"3c9ef272bab741408a2bf1e649898881",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":68,
              "y":507},
            "size":{
              "width":319,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33935e9b0c4d4f689b477773d76df6e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":68,
                  "y":507},
                "size":{
                  "width":319,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（完成）买手/u13.png"}},
{
          "id":"99774eef37694bf7bdd9686ffdbf8177",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":67,
              "y":544},
            "size":{
              "width":194,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d005d2b9dd743f699a7d0dec9001f92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":67,
                  "y":544},
                "size":{
                  "width":194,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（完成）买手/u15.png"}},
{
          "id":"9d2ebacb6ece45599011b5e69cb3bd77",
          "label":"Tab",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":68,
              "y":453},
            "size":{
              "width":66,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54df8d95906b49ed96864a9d3a6d2432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":68,
                  "y":453},
                "size":{
                  "width":66,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（发货）/tab_u17.png"}},
{
          "id":"ab057d83ef8740f48f21b0678ea11f82",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":68,
              "y":477},
            "size":{
              "width":320,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cbfd9b560f14919b36dd78a8d2d25a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":68,
                  "y":477},
                "size":{
                  "width":320,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新建私信",
                      "target":{
                        "targetType":"page",
                        "url":"新建私信.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单详细（发货）/u19.png"}},
{
          "id":"b3f51b349f574e309c996b5741886a01",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":279,
              "y":548},
            "size":{
              "width":100,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951d7a2ebf7747b48b4556efc2ee24c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":279,
                  "y":548},
                "size":{
                  "width":100,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详细（完成）买手",
                      "target":{
                        "targetType":"page",
                        "url":"订单详细（完成）买手.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付页面3/button_u35.png",
            "mouseOver~":"images/支付页面3/button_u35_mouseOver.png"}},
{
          "id":"635874cbf3af490397ce03078a9e5b26",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "25d4eac930d5475dbe7600255fbab999":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "856a9923abec414f88d872acc8ab35b3":{
      "scriptId":"u5"},
    "7832d2d4f1dd4f3d99f6fa9df15330f4":{
      "scriptId":"u6"},
    "475107178af84a529f3d91300a9c3ba3":{
      "scriptId":"u7"},
    "19f3e05fab9140c898efc7b7b621d63a":{
      "scriptId":"u8"},
    "aaa963c489e841528de6dc7a7c8f6a0a":{
      "scriptId":"u9"},
    "2ab2589d06d5454b98f014b79e136a8c":{
      "scriptId":"u10"},
    "c77fc42f8ad1460d93b038d94ed986de":{
      "scriptId":"u11"},
    "865a97d801e24caeb03f92be2223eb59":{
      "scriptId":"u12"},
    "3c9ef272bab741408a2bf1e649898881":{
      "scriptId":"u13"},
    "33935e9b0c4d4f689b477773d76df6e0":{
      "scriptId":"u14"},
    "99774eef37694bf7bdd9686ffdbf8177":{
      "scriptId":"u15"},
    "0d005d2b9dd743f699a7d0dec9001f92":{
      "scriptId":"u16"},
    "9d2ebacb6ece45599011b5e69cb3bd77":{
      "scriptId":"u17"},
    "54df8d95906b49ed96864a9d3a6d2432":{
      "scriptId":"u18"},
    "ab057d83ef8740f48f21b0678ea11f82":{
      "scriptId":"u19"},
    "1cbfd9b560f14919b36dd78a8d2d25a9":{
      "scriptId":"u20"},
    "b3f51b349f574e309c996b5741886a01":{
      "scriptId":"u21"},
    "951d7a2ebf7747b48b4556efc2ee24c2":{
      "scriptId":"u22"},
    "635874cbf3af490397ce03078a9e5b26":{
      "scriptId":"u23",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u24"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u25"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u26"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u27"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u28"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u29"}}}});