$axure.loadCurrentPage({
  "url":"我的账本.html",
  "generationDate":new Date(1408680671075.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8a61a818588845c6bd189f8343a89d5b",
    "type":"Axure:Page",
    "name":"我的账本",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb323fdcd7f84bf5ac3f886a7ff78057",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"cc842b10f93e460b8269d9199788ad4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":65,
              "y":179},
            "size":{
              "width":321,
              "height":418}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa2116cbac44198a05c6093e893ae07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":65,
                  "y":179},
                "size":{
                  "width":321,
                  "height":418}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账本/u5.png"}},
{
          "id":"0d64e5a0e8964f0b8516d3013296c584",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":197},
            "size":{
              "width":78,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d63a9494ab14048a9b50a644c55dfc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":197},
                "size":{
                  "width":78,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的（登录后）/u53.png"}},
{
          "id":"bdfbfb58e453472086ce37ddff7f0b22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":201,
              "y":215},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b036d9040d443fb8355d628c27a3875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":201,
                  "y":215},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4cf88adf7d049c199e1bab0d1481240",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":66,
              "y":278},
            "size":{
              "width":322,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff6b5f780b446cbbf20a36dca0f5169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":66,
                  "y":278},
                "size":{
                  "width":322,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 账单明细 淡入淡出 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["83f3e7208d1243df94c3758ed2f61ff7"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的账本/u11.png"}},
{
          "id":"f9c421798aa44284ae8d10138d96288b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":66,
              "y":327},
            "size":{
              "width":320,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccafe8bed99b42cd8cfc66de6d1c9d58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":66,
                  "y":327},
                "size":{
                  "width":320,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已发布的订单",
                      "target":{
                        "targetType":"page",
                        "url":"已发布的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的账本/u13.png"}},
{
          "id":"83f3e7208d1243df94c3758ed2f61ff7",
          "label":"账单明细",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":66,
              "y":327},
            "size":{
              "width":320,
              "height":270},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b3865a5b4943465293f967d249b36262",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2bdfeaa82c7d475fab62ab5a637bcea3",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "size":{
                      "width":320,
                      "height":270}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ff50687b6504c13b9c305a7dbe6bd3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7},
                        "size":{
                          "width":320,
                          "height":270}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的账本/u16.png"}},
{
                  "id":"a62fa9a8c3d94867a0a33acdb8329380",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":11},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"600c5d8084be456387fa28e6cad52920",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":11},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6bf69737aac343fd8456cbd07af3d481",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":2,
                      "y":40},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b102f772ad024d809cc23b2cb458e1d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":2,
                          "y":40},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c18a1b898f9c4555abf62d708f1e3da8",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":69},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1dc4b358309e4817a14d90ee68d38d81",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":69},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"98442efc2a8446b5990e2fbccc386219",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":2,
                      "y":98},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25443080277d479fb0b55746a0fcd18d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":2,
                          "y":98},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ce6b225cc13742288198a757fbd2f1d6",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":127},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d8bcf1c0b214fb28852823988ad884f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":127},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ff5000f001104d95a08026fec146d85b",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":2,
                      "y":156},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3847104c0251431fac0f158765af61f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":2,
                          "y":156},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1ae19a82c9764b7cbc20278281f7796b",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":185},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a636a9437e1549be8ad09a7e39c03fb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":185},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"91d5262a727145c8a7bf44c8a7342b08",
                  "label":"",
                  "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":2,
                      "y":214},
                    "size":{
                      "width":320,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60868ac5113d44eaa622736b080fabf1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83f3e7208d1243df94c3758ed2f61ff7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":2,
                          "y":214},
                        "size":{
                          "width":320,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"8e422abebe504facba750f95725c337f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "fb323fdcd7f84bf5ac3f886a7ff78057":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "cc842b10f93e460b8269d9199788ad4b":{
      "scriptId":"u5"},
    "aaa2116cbac44198a05c6093e893ae07":{
      "scriptId":"u6"},
    "0d64e5a0e8964f0b8516d3013296c584":{
      "scriptId":"u7"},
    "0d63a9494ab14048a9b50a644c55dfc5":{
      "scriptId":"u8"},
    "bdfbfb58e453472086ce37ddff7f0b22":{
      "scriptId":"u9"},
    "9b036d9040d443fb8355d628c27a3875":{
      "scriptId":"u10"},
    "e4cf88adf7d049c199e1bab0d1481240":{
      "scriptId":"u11"},
    "7ff6b5f780b446cbbf20a36dca0f5169":{
      "scriptId":"u12"},
    "f9c421798aa44284ae8d10138d96288b":{
      "scriptId":"u13"},
    "ccafe8bed99b42cd8cfc66de6d1c9d58":{
      "scriptId":"u14"},
    "83f3e7208d1243df94c3758ed2f61ff7":{
      "scriptId":"u15"},
    "2bdfeaa82c7d475fab62ab5a637bcea3":{
      "scriptId":"u16"},
    "1ff50687b6504c13b9c305a7dbe6bd3a":{
      "scriptId":"u17"},
    "a62fa9a8c3d94867a0a33acdb8329380":{
      "scriptId":"u18"},
    "600c5d8084be456387fa28e6cad52920":{
      "scriptId":"u19"},
    "6bf69737aac343fd8456cbd07af3d481":{
      "scriptId":"u20"},
    "b102f772ad024d809cc23b2cb458e1d4":{
      "scriptId":"u21"},
    "c18a1b898f9c4555abf62d708f1e3da8":{
      "scriptId":"u22"},
    "1dc4b358309e4817a14d90ee68d38d81":{
      "scriptId":"u23"},
    "98442efc2a8446b5990e2fbccc386219":{
      "scriptId":"u24"},
    "25443080277d479fb0b55746a0fcd18d":{
      "scriptId":"u25"},
    "ce6b225cc13742288198a757fbd2f1d6":{
      "scriptId":"u26"},
    "6d8bcf1c0b214fb28852823988ad884f":{
      "scriptId":"u27"},
    "ff5000f001104d95a08026fec146d85b":{
      "scriptId":"u28"},
    "3847104c0251431fac0f158765af61f4":{
      "scriptId":"u29"},
    "1ae19a82c9764b7cbc20278281f7796b":{
      "scriptId":"u30"},
    "a636a9437e1549be8ad09a7e39c03fb6":{
      "scriptId":"u31"},
    "91d5262a727145c8a7bf44c8a7342b08":{
      "scriptId":"u32"},
    "60868ac5113d44eaa622736b080fabf1":{
      "scriptId":"u33"},
    "8e422abebe504facba750f95725c337f":{
      "scriptId":"u34",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u35"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u36"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u37"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u38"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u39"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u40"}}}});