$axure.loadCurrentPage({
  "url":"我的预购订单_1.html",
  "generationDate":new Date(1408595824736.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f518eee7b83448da872c64c732499634",
    "type":"Axure:Page",
    "name":"我的预购订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18492eebaaac41d588b6b6769f33a9ad",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"052c9c4a81864fce97f50b1351187630",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":66,
              "y":147},
            "size":{
              "width":322,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32740cd7404643578a20e065d73f1509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":66,
                  "y":147},
                "size":{
                  "width":322,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清单一览/u21.png"}},
{
          "id":"646f149c3f7f4ab1928f1fc5f7d692a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":60,
              "y":148},
            "size":{
              "width":33,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b07f2509c441d2955870f7e11f19d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":60,
                  "y":148},
                "size":{
                  "width":33,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的预购订单/u15.png"}},
{
          "id":"81f03d1aa31e4f91b6a1f65a6fb845ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":93,
              "y":152},
            "size":{
              "width":28,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c98b32e8a1461bb1348653be488a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":93,
                  "y":152},
                "size":{
                  "width":28,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69332d82f9184e73908dfbf1673ef0a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h4",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":187,
              "y":155},
            "size":{
              "width":75,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25c043223b774091a72d68a0ca4c0d21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":187,
                  "y":155},
                "size":{
                  "width":75,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cea3448da5849cfafe4a55119335cd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":343,
              "y":150},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e942ef30e2dc47819309dbc3928563e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":343,
                  "y":150},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建订单",
                      "target":{
                        "targetType":"page",
                        "url":"创建订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u35.png"}},
{
          "id":"5ba1ebeb32464d4a88a536e69d207cee",
          "label":"未发布的订单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":187},
            "size":{
              "width":321,
              "height":410}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1ffd3a1d3e8d4f89aa219f46c66e343e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"380adbdd39764de1aba21c6f835da2ad",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":49,
                      "y":12},
                    "size":{
                      "width":272,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f3e4fe9b6c4474ab466b7e442392d49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":49,
                          "y":12},
                        "size":{
                          "width":272,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 创建订单",
                              "target":{
                                "targetType":"page",
                                "url":"创建订单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"fafd7b28d6bf497bace27b6b92875320",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":49,
                      "y":88},
                    "size":{
                      "width":272,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abbe29ea83f14b12a7c68cdab2346924",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":49,
                          "y":88},
                        "size":{
                          "width":272,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改订单",
                              "target":{
                                "targetType":"page",
                                "url":"修改订单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"789dac5ff6814286bd0f77234a71cf41",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":49,
                      "y":167},
                    "size":{
                      "width":272,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"78edfecf753646e7bf9bf71d4b2a4c05",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":49,
                          "y":167},
                        "size":{
                          "width":272,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"9e24bb9d6b53447cac1923ba8246ad61",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":49,
                      "y":248},
                    "size":{
                      "width":270,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44c4d683ad034eba9c596172f30b068d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":49,
                          "y":248},
                        "size":{
                          "width":270,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"093924684c4440a6917d7f4dab98e1c3",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":49,
                      "y":328},
                    "size":{
                      "width":270,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d64998b6f66b416dba8514516df6f896",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":49,
                          "y":328},
                        "size":{
                          "width":270,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"6c8929ee30ab4194902dbaefcd661bdb",
                  "label":"",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":81},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的预购订单/u34_line.png"}},
{
                  "id":"2f01b11945c2403eba1b65089afaf90d",
                  "label":"",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":157},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的预购订单/u34_line.png"}},
{
                  "id":"f2dd16e1d2b247a0af29d8d897c1b7fb",
                  "label":"",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":236},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的预购订单/u34_line.png"}},
{
                  "id":"5d65a0c480f04de3905637ad73a788b0",
                  "label":"",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":317},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的预购订单/u34_line.png"}},
{
                  "id":"3d287b98c2ff489f8934727ca508c5e1",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":49,
                      "y":407},
                    "size":{
                      "width":282,
                      "height":69},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c8a0b27dc1740de939189d1b2c8d9ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":49,
                          "y":407},
                        "size":{
                          "width":282,
                          "height":69},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"adcb8d2d086d43b0b7935e56f0319304",
                  "label":"",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":397},
                    "size":{
                      "width":321,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的预购订单/u34_line.png"}},
{
                  "id":"e8bec256f84f4503a17238c5bd37032d",
                  "label":"Loading Large",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":142,
                      "y":479},
                    "size":{
                      "width":32,
                      "height":32},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06053e46d73043419632bd5dabcc40ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":142,
                          "y":479},
                        "size":{
                          "width":32,
                          "height":32},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的预购订单/loading_large_u41.gif"}},
{
                  "id":"1f4ca31b63324e7caaf5b6d3158fb878",
                  "label":"1",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":19,
                      "y":38},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d04e867566844449d834a0a4629cb91",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":19,
                          "y":38},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"3e2c9e0f0f22419fa7ae0d6ce09bb750",
                  "label":"2",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":19,
                      "y":114},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"947ed9da9cd547cb9f5557e174a7c43b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":19,
                          "y":114},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"b152d851cd0c48afbc3f28b83b8aac6d",
                  "label":"3",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":19,
                      "y":194},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4551a9b4ad6446d0beda0bad5273d9cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":19,
                          "y":194},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"c1fc7dceb3a5421c995e31489f7809e4",
                  "label":"4",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":19,
                      "y":274},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f90f18d4648495f95d9baab8e1913f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":19,
                          "y":274},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"6b9f0d2c044b4ed0ba7f43fced4a7f4e",
                  "label":"5",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":19,
                      "y":354},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3478aa07275d421aaaa7947f7b2a3e31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":19,
                          "y":354},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"6794f536aa64425399b6aef681421c92",
                  "label":"6",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":19,
                      "y":432},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e05ad0fafc8a4dcab1fc5487706bd57e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":19,
                          "y":432},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"fec832376f804c01a77e9fe1c956b35c",
                  "label":"Button",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"7px",
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00CCFF}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "location":{
                      "x":9,
                      "y":3},
                    "size":{
                      "width":40,
                      "height":17},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"5.666672"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6a831b6eba94e69a33d1cc38c3181b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"7px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF00CCFF}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "location":{
                          "x":9,
                          "y":3},
                        "size":{
                          "width":40,
                          "height":17},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"5.666672"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 选中状态值 1 = &quot;true&quot;, 且<br> 选中状态值 2 = &quot;true&quot;, 且<br> 选中状态值 3 = &quot;true&quot;, 且<br> 选中状态值 4 = &quot;true&quot;, 且<br> 选中状态值 5 = &quot;true&quot;, 且<br> 选中状态值 6 = &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["1f4ca31b63324e7caaf5b6d3158fb878"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["3e2c9e0f0f22419fa7ae0d6ce09bb750"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["b152d851cd0c48afbc3f28b83b8aac6d"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["c1fc7dceb3a5421c995e31489f7809e4"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6b9f0d2c044b4ed0ba7f43fced4a7f4e"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]},
{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6794f536aa64425399b6aef681421c92"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的预购订单_1/button_u55.png",
                    "mouseOver~":"images/我的预购订单_1/button_u55_mouseOver.png"}},
{
                  "id":"5f845f6fd68b491f900e1f314e0e2749",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":213,
                      "y":38},
                    "size":{
                      "width":77,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e09a7d47451f44b88f391a6af5ca9796",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":213,
                          "y":38},
                        "size":{
                          "width":77,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"a68bfecc998a4dc6885fcf0e9d1291f7",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":212,
                      "y":118},
                    "size":{
                      "width":77,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"000af436f31949eb9d1d7ee865ee7695",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":212,
                          "y":118},
                        "size":{
                          "width":77,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"950f0f5ba2234b79a34b3c7b26c9f869",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":211,
                      "y":198},
                    "size":{
                      "width":77,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd5b735b32874682a03ccab3f90ca206",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":211,
                          "y":198},
                        "size":{
                          "width":77,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"16dad1eeae6f4f09a5bd5d044bc78684",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":210,
                      "y":278},
                    "size":{
                      "width":77,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3938346e44494c2abd114f11f5fae795",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":210,
                          "y":278},
                        "size":{
                          "width":77,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"44cd93f7182e40608c8e563c23ae267b",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":211,
                      "y":354},
                    "size":{
                      "width":77,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"722bcec3a54440e0b34d611fae1e4c96",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":211,
                          "y":354},
                        "size":{
                          "width":77,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"785b6aba2d284dd18c6d29c190b63514",
                  "label":"Link",
                  "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":212,
                      "y":444},
                    "size":{
                      "width":77,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48cd53ffb4724cfbae52ca548fbb704b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ba1ebeb32464d4a88a536e69d207cee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":212,
                          "y":444},
                        "size":{
                          "width":77,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"3ff5e63ddb664ee18c6482bc32accc48",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":103,
              "y":563},
            "size":{
              "width":230,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d18a6f74717e4738b3c88af7b6f3e8a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":103,
                  "y":563},
                "size":{
                  "width":230,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"images/我的预购订单/button_u69_mouseOver.png"}}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u1.png"}},
{
            "id":"901bf5fad6b24aa28879e999b676ff29",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF99CCFF},
              "location":{
                "x":65,
                "y":120},
              "size":{
                "width":322,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d3c8f6ba4db54b7180dda95fdac9eb33",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF99CCFF},
                  "location":{
                    "x":65,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u11.png"}},
{
            "id":"3ae9b2d30d6c4e47974da0f1f40183cb",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":335,
                "y":123},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"238713c20ad94bb7beb171261a931644",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":335,
                    "y":123},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}},
{
            "id":"3245d7b29b184ae8bb4282155a41dc68",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":311,
                "y":122},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2483113f29fe4494a91ab6354144197f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":311,
                    "y":122},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u15.png"}},
{
            "id":"29b6cbaf58714338a233837b0fc50538",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":289,
                "y":122},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d12b80914ce141e881fc147bcdba67d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":289,
                    "y":122},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u17.png"}},
{
            "id":"df8c8bfcfb7248908696b24c74cdebc7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":359,
                "y":123},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"492530becc094a6f88000e4ef95c81b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":359,
                    "y":123},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u19.png"}}]}}},
  "objectPaths":{
    "18492eebaaac41d588b6b6769f33a9ad":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "901bf5fad6b24aa28879e999b676ff29":{
        "scriptId":"u3"},
      "d3c8f6ba4db54b7180dda95fdac9eb33":{
        "scriptId":"u4"},
      "3ae9b2d30d6c4e47974da0f1f40183cb":{
        "scriptId":"u5"},
      "238713c20ad94bb7beb171261a931644":{
        "scriptId":"u6"},
      "3245d7b29b184ae8bb4282155a41dc68":{
        "scriptId":"u7"},
      "2483113f29fe4494a91ab6354144197f":{
        "scriptId":"u8"},
      "29b6cbaf58714338a233837b0fc50538":{
        "scriptId":"u9"},
      "d12b80914ce141e881fc147bcdba67d8":{
        "scriptId":"u10"},
      "df8c8bfcfb7248908696b24c74cdebc7":{
        "scriptId":"u11"},
      "492530becc094a6f88000e4ef95c81b1":{
        "scriptId":"u12"}},
    "052c9c4a81864fce97f50b1351187630":{
      "scriptId":"u13"},
    "32740cd7404643578a20e065d73f1509":{
      "scriptId":"u14"},
    "646f149c3f7f4ab1928f1fc5f7d692a6":{
      "scriptId":"u15"},
    "95b07f2509c441d2955870f7e11f19d4":{
      "scriptId":"u16"},
    "81f03d1aa31e4f91b6a1f65a6fb845ec":{
      "scriptId":"u17"},
    "78c98b32e8a1461bb1348653be488a4f":{
      "scriptId":"u18"},
    "69332d82f9184e73908dfbf1673ef0a8":{
      "scriptId":"u19"},
    "25c043223b774091a72d68a0ca4c0d21":{
      "scriptId":"u20"},
    "4cea3448da5849cfafe4a55119335cd6":{
      "scriptId":"u21"},
    "e942ef30e2dc47819309dbc3928563e2":{
      "scriptId":"u22"},
    "5ba1ebeb32464d4a88a536e69d207cee":{
      "scriptId":"u23"},
    "380adbdd39764de1aba21c6f835da2ad":{
      "scriptId":"u24"},
    "1f3e4fe9b6c4474ab466b7e442392d49":{
      "scriptId":"u25"},
    "fafd7b28d6bf497bace27b6b92875320":{
      "scriptId":"u26"},
    "abbe29ea83f14b12a7c68cdab2346924":{
      "scriptId":"u27"},
    "789dac5ff6814286bd0f77234a71cf41":{
      "scriptId":"u28"},
    "78edfecf753646e7bf9bf71d4b2a4c05":{
      "scriptId":"u29"},
    "9e24bb9d6b53447cac1923ba8246ad61":{
      "scriptId":"u30"},
    "44c4d683ad034eba9c596172f30b068d":{
      "scriptId":"u31"},
    "093924684c4440a6917d7f4dab98e1c3":{
      "scriptId":"u32"},
    "d64998b6f66b416dba8514516df6f896":{
      "scriptId":"u33"},
    "6c8929ee30ab4194902dbaefcd661bdb":{
      "scriptId":"u34"},
    "2f01b11945c2403eba1b65089afaf90d":{
      "scriptId":"u35"},
    "f2dd16e1d2b247a0af29d8d897c1b7fb":{
      "scriptId":"u36"},
    "5d65a0c480f04de3905637ad73a788b0":{
      "scriptId":"u37"},
    "3d287b98c2ff489f8934727ca508c5e1":{
      "scriptId":"u38"},
    "7c8a0b27dc1740de939189d1b2c8d9ac":{
      "scriptId":"u39"},
    "adcb8d2d086d43b0b7935e56f0319304":{
      "scriptId":"u40"},
    "e8bec256f84f4503a17238c5bd37032d":{
      "scriptId":"u41"},
    "06053e46d73043419632bd5dabcc40ef":{
      "scriptId":"u42"},
    "1f4ca31b63324e7caaf5b6d3158fb878":{
      "scriptId":"u43"},
    "0d04e867566844449d834a0a4629cb91":{
      "scriptId":"u44"},
    "3e2c9e0f0f22419fa7ae0d6ce09bb750":{
      "scriptId":"u45"},
    "947ed9da9cd547cb9f5557e174a7c43b":{
      "scriptId":"u46"},
    "b152d851cd0c48afbc3f28b83b8aac6d":{
      "scriptId":"u47"},
    "4551a9b4ad6446d0beda0bad5273d9cd":{
      "scriptId":"u48"},
    "c1fc7dceb3a5421c995e31489f7809e4":{
      "scriptId":"u49"},
    "1f90f18d4648495f95d9baab8e1913f0":{
      "scriptId":"u50"},
    "6b9f0d2c044b4ed0ba7f43fced4a7f4e":{
      "scriptId":"u51"},
    "3478aa07275d421aaaa7947f7b2a3e31":{
      "scriptId":"u52"},
    "6794f536aa64425399b6aef681421c92":{
      "scriptId":"u53"},
    "e05ad0fafc8a4dcab1fc5487706bd57e":{
      "scriptId":"u54"},
    "fec832376f804c01a77e9fe1c956b35c":{
      "scriptId":"u55"},
    "f6a831b6eba94e69a33d1cc38c3181b1":{
      "scriptId":"u56"},
    "5f845f6fd68b491f900e1f314e0e2749":{
      "scriptId":"u57"},
    "e09a7d47451f44b88f391a6af5ca9796":{
      "scriptId":"u58"},
    "a68bfecc998a4dc6885fcf0e9d1291f7":{
      "scriptId":"u59"},
    "000af436f31949eb9d1d7ee865ee7695":{
      "scriptId":"u60"},
    "950f0f5ba2234b79a34b3c7b26c9f869":{
      "scriptId":"u61"},
    "dd5b735b32874682a03ccab3f90ca206":{
      "scriptId":"u62"},
    "16dad1eeae6f4f09a5bd5d044bc78684":{
      "scriptId":"u63"},
    "3938346e44494c2abd114f11f5fae795":{
      "scriptId":"u64"},
    "44cd93f7182e40608c8e563c23ae267b":{
      "scriptId":"u65"},
    "722bcec3a54440e0b34d611fae1e4c96":{
      "scriptId":"u66"},
    "785b6aba2d284dd18c6d29c190b63514":{
      "scriptId":"u67"},
    "48cd53ffb4724cfbae52ca548fbb704b":{
      "scriptId":"u68"},
    "3ff5e63ddb664ee18c6482bc32accc48":{
      "scriptId":"u69"},
    "d18a6f74717e4738b3c88af7b6f3e8a3":{
      "scriptId":"u70"}}});