$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1408680671730.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2d23b80cd969498e8eee3c8433dd34e5",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6568bec449b84afea45220b424840c2e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f8ce3025faf24c03ac87966ecb347165"},
{
          "id":"386a8f0fe5eb4fb8b60e13c15330a0c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":64,
              "y":179},
            "size":{
              "width":323,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f63da5f42fef4d0dae56125852b526c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":64,
                  "y":179},
                "size":{
                  "width":323,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u5.png"}},
{
          "id":"bd07b11d37634dd89f34823982b7bd3b",
          "label":"Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":106,
              "y":339},
            "size":{
              "width":229,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5.666672"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d06bac714ea436087ca976ed7b38f07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":106,
                  "y":339},
                "size":{
                  "width":229,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5.666672"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/button_u7.png",
            "mouseOver~":"images/登录/button_u7_mouseOver.png"}},
{
          "id":"e0a15121d5b84ca2881d32ef9751d70d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":106,
              "y":197},
            "size":{
              "width":229,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68c3629445f24185bc702b20668ebcf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":106,
                  "y":197},
                "size":{
                  "width":229,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u9.png"}},
{
          "id":"8e1123e773e5479fab908b08d246706b",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":114,
              "y":212},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 用户名 = &quot;请输入用户名&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["8e1123e773e5479fab908b08d246706b"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"请输入用户名",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 用户名 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8e1123e773e5479fab908b08d246706b"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 用户名 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["8e1123e773e5479fab908b08d246706b"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 密码 = &quot;请输入密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d62ff931122946b88ed766ed7c028bba"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入密码",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"d62ff931122946b88ed766ed7c028bba",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":114,
              "y":263},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 密码 = &quot;请输入密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d62ff931122946b88ed766ed7c028bba"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"请输入密码",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 密码 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d62ff931122946b88ed766ed7c028bba"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 密码 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d62ff931122946b88ed766ed7c028bba"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 密码 = &quot;请输入密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d62ff931122946b88ed766ed7c028bba"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入密码",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"eb1a60c439ec446da0a20231e08c4980",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":274,
              "y":389},
            "size":{
              "width":61,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e396e29463174e1ea2762d0b23d3f18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":274,
                  "y":389},
                "size":{
                  "width":61,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f677a737941c48ffbf119a1de081ebc4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"54ba2665932c416d9a35042a8371c0fd"}]}},
  "masters":{
    "f8ce3025faf24c03ac87966ecb347165":{
      "packageId":"f8ce3025faf24c03ac87966ecb347165",
      "type":"Axure:Master",
      "name":"手机不带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8dc17a57d71a42e4b7ef940d37d46042",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da12161cc5c444caad5a5bbf1e421b92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"ce91cf98290e44a1ad8a9f079025e7ee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":64,
                "y":120},
              "size":{
                "width":322,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53a4193308e14412a7bba1c2f3336f6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":64,
                    "y":120},
                  "size":{
                    "width":322,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "54ba2665932c416d9a35042a8371c0fd":{
      "packageId":"54ba2665932c416d9a35042a8371c0fd",
      "type":"Axure:Master",
      "name":"头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":104,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":104,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"94cedad53c8240e7af186aba7201be8b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":73,
                "y":149},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c0b6ea0e91d4e26a56c66d1b5393392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":73,
                    "y":149},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的代购订单/u42.png"}}]}}},
  "objectPaths":{
    "6568bec449b84afea45220b424840c2e":{
      "scriptId":"u0",
      "8dc17a57d71a42e4b7ef940d37d46042":{
        "scriptId":"u1"},
      "da12161cc5c444caad5a5bbf1e421b92":{
        "scriptId":"u2"},
      "ce91cf98290e44a1ad8a9f079025e7ee":{
        "scriptId":"u3"},
      "53a4193308e14412a7bba1c2f3336f6d":{
        "scriptId":"u4"}},
    "386a8f0fe5eb4fb8b60e13c15330a0c0":{
      "scriptId":"u5"},
    "f63da5f42fef4d0dae56125852b526c1":{
      "scriptId":"u6"},
    "bd07b11d37634dd89f34823982b7bd3b":{
      "scriptId":"u7"},
    "1d06bac714ea436087ca976ed7b38f07":{
      "scriptId":"u8"},
    "e0a15121d5b84ca2881d32ef9751d70d":{
      "scriptId":"u9"},
    "68c3629445f24185bc702b20668ebcf3":{
      "scriptId":"u10"},
    "8e1123e773e5479fab908b08d246706b":{
      "scriptId":"u11"},
    "d62ff931122946b88ed766ed7c028bba":{
      "scriptId":"u12"},
    "eb1a60c439ec446da0a20231e08c4980":{
      "scriptId":"u13"},
    "e396e29463174e1ea2762d0b23d3f18d":{
      "scriptId":"u14"},
    "f677a737941c48ffbf119a1de081ebc4":{
      "scriptId":"u15",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u16"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u17"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u18"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u19"},
      "94cedad53c8240e7af186aba7201be8b":{
        "scriptId":"u20"},
      "8c0b6ea0e91d4e26a56c66d1b5393392":{
        "scriptId":"u21"}}}});