$axure.loadCurrentPage({
  "url":"我的订单一览.html",
  "generationDate":new Date(1408680670235.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8b564a6821354d4d829b1a82b2704452",
    "type":"Axure:Page",
    "name":"我的订单一览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5fb00600d979457f959f0cb719848da6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5e0f6785936c4012b80ddc166e0c4560"},
{
          "id":"692613f2c93f472ab89f05b3f0421e12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":65,
              "y":187},
            "size":{
              "width":323,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b01d6f353314a6da031940a14a1cb39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":65,
                  "y":187},
                "size":{
                  "width":323,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单一览/u15.png"}},
{
          "id":"6a3f098850344a3d8cbf37fc425197c4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":64,
              "y":187},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c30897d0b9b442b58b9a3207c21b2bfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":64,
                  "y":187},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已发布的订单",
                      "target":{
                        "targetType":"page",
                        "url":"已发布的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u17.png"}},
{
          "id":"d50f6eb5a8254f60bfe779f6a17250bd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":64,
              "y":236},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"298ec1ba47de4769b5a9ca69a345bc14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":64,
                  "y":236},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的预购订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的预购订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u17.png"}},
{
          "id":"1058885240924a3cbc9efb7056b8c19f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":64,
              "y":285},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ffc8efe3df04122ad454e085335677e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":64,
                  "y":285},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已完成订单",
                      "target":{
                        "targetType":"page",
                        "url":"已完成订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u17.png"}},
{
          "id":"b5ae69201dc3449d83d28fd8eb671a51",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0de6210566dd4614a4f81872b4896af2"},
{
          "id":"b85ff612a05c4016bd883358c1bba49a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":354,
              "y":150},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3eb851e6494480da6c3f4b4f4a33b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":354,
                  "y":150},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建订单",
                      "target":{
                        "targetType":"page",
                        "url":"创建订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u30.png"}},
{
          "id":"be57c01fe8af4ded85a729ba2dd16891",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "location":{
              "x":66,
              "y":334},
            "size":{
              "width":324,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ee9b7e4b61e4418b63985cb0d677422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "location":{
                  "x":66,
                  "y":334},
                "size":{
                  "width":324,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的代购订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的代购订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单一览/u17.png"}}]}},
  "masters":{
    "5e0f6785936c4012b80ddc166e0c4560":{
      "packageId":"5e0f6785936c4012b80ddc166e0c4560",
      "type":"Axure:Master",
      "name":"手机带菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1b205b6aeef2413b88e1d633ea7511d6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":64,
                "y":570},
              "size":{
                "width":322,
                "height":30},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53e62992bfdb47b683c106941fc81ec0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":64,
                    "y":570},
                  "size":{
                    "width":322,
                    "height":30},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u1.png"}},
{
            "id":"f6006b5d5baa46999c7cf32d94d6f166",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "size":{
                "width":450,
                "height":731}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c3ab424966d246fdb5e45eb4afcdf778",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "size":{
                    "width":450,
                    "height":731}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u3.png"}},
{
            "id":"376607bd7c274dafa220f6c087c4779c",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":66,
                "y":570},
              "size":{
                "width":80,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"660425e3d91c4ea2b44248e29d14fed2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":66,
                    "y":570},
                  "size":{
                    "width":80,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["376607bd7c274dafa220f6c087c4779c"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn1_u5.png",
              "selected~":"images/主页/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/主页/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ef426acdd5884c2580d1f8fecc379796",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":305,
                "y":570},
              "size":{
                "width":81,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9dbd829d9824183a1338cbe3aa031b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":305,
                    "y":570},
                  "size":{
                    "width":81,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ef426acdd5884c2580d1f8fecc379796"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的（登录后）",
                        "target":{
                          "targetType":"page",
                          "url":"我的（登录后）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn4_u7.png",
              "selected~":"images/主页/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/主页/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"80012608a8d44d698ecac65c8e170cbf",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":145,
                "y":570},
              "size":{
                "width":81,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee8f8c5e6ca346bdba5725c2383f372b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":145,
                    "y":570},
                  "size":{
                    "width":81,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["80012608a8d44d698ecac65c8e170cbf"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 清单一览",
                        "target":{
                          "targetType":"page",
                          "url":"清单一览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn4_u7.png",
              "selected~":"images/主页/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/主页/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"a51c84b091884f8bb0b2d6b764e32be6",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                "selected":{
                  "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF}]},
              "location":{
                "x":226,
                "y":570},
              "size":{
                "width":80,
                "height":30},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b483f339b018443094743646a184d0a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "baseStyle":"6bdaed540ceb4195a0b5acc57a677611",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"d23b879e3de7439d8ae046def634dc9f"},
                    "selected":{
                      "baseStyle":"b4bee205229d4ed1911de33d79ddff1a"}},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF}]},
                  "location":{
                    "x":226,
                    "y":570},
                  "size":{
                    "width":80,
                    "height":30},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 选中状态值 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["a51c84b091884f8bb0b2d6b764e32be6"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的订单一览",
                        "target":{
                          "targetType":"page",
                          "url":"我的订单一览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/主页/segmentedbtn1_u5.png",
              "selected~":"images/主页/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/主页/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ec15bb5d8bd049209662ccb717cc1a52",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "baseStyle":"627587b6038d43cca051c114ac41ad32",
              "location":{
                "x":66,
                "y":120},
              "size":{
                "width":320,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7b6262ff7f0444988f65a72dc522603",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "baseStyle":"627587b6038d43cca051c114ac41ad32",
                  "location":{
                    "x":66,
                    "y":120},
                  "size":{
                    "width":320,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u13.png"}}]}},
    "0de6210566dd4614a4f81872b4896af2":{
      "packageId":"0de6210566dd4614a4f81872b4896af2",
      "type":"Axure:Master",
      "name":"头部一级",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc1cde7cbfd44a429c63bc03d2dad238",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFCC00},
{
                    "color":0xFFFFCC00},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":66,
                "y":146},
              "size":{
                "width":320,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFCC00}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d541aa5abb104593ade50bf5a901d62a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFCC00},
{
                        "color":0xFFFFCC00},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":66,
                    "y":146},
                  "size":{
                    "width":320,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFCC00}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"48c043db19e443daaad28b6565e9af35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":78,
                "y":150},
              "size":{
                "width":30,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5652abe7da524d7da0ee59ff511d08e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":78,
                    "y":150},
                  "size":{
                    "width":30,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"4bd8bc1c9de9428c9013ab06e59631c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h4",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "location":{
                "x":108,
                "y":146},
              "size":{
                "width":72,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"afa01676eda8434c8bc3894106940c4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":108,
                    "y":146},
                  "size":{
                    "width":72,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "5fb00600d979457f959f0cb719848da6":{
      "scriptId":"u0",
      "1b205b6aeef2413b88e1d633ea7511d6":{
        "scriptId":"u1"},
      "53e62992bfdb47b683c106941fc81ec0":{
        "scriptId":"u2"},
      "f6006b5d5baa46999c7cf32d94d6f166":{
        "scriptId":"u3"},
      "c3ab424966d246fdb5e45eb4afcdf778":{
        "scriptId":"u4"},
      "376607bd7c274dafa220f6c087c4779c":{
        "scriptId":"u5"},
      "660425e3d91c4ea2b44248e29d14fed2":{
        "scriptId":"u6"},
      "ef426acdd5884c2580d1f8fecc379796":{
        "scriptId":"u7"},
      "b9dbd829d9824183a1338cbe3aa031b7":{
        "scriptId":"u8"},
      "80012608a8d44d698ecac65c8e170cbf":{
        "scriptId":"u9"},
      "ee8f8c5e6ca346bdba5725c2383f372b":{
        "scriptId":"u10"},
      "a51c84b091884f8bb0b2d6b764e32be6":{
        "scriptId":"u11"},
      "b483f339b018443094743646a184d0a7":{
        "scriptId":"u12"},
      "ec15bb5d8bd049209662ccb717cc1a52":{
        "scriptId":"u13"},
      "c7b6262ff7f0444988f65a72dc522603":{
        "scriptId":"u14"}},
    "692613f2c93f472ab89f05b3f0421e12":{
      "scriptId":"u15"},
    "1b01d6f353314a6da031940a14a1cb39":{
      "scriptId":"u16"},
    "6a3f098850344a3d8cbf37fc425197c4":{
      "scriptId":"u17"},
    "c30897d0b9b442b58b9a3207c21b2bfd":{
      "scriptId":"u18"},
    "d50f6eb5a8254f60bfe779f6a17250bd":{
      "scriptId":"u19"},
    "298ec1ba47de4769b5a9ca69a345bc14":{
      "scriptId":"u20"},
    "1058885240924a3cbc9efb7056b8c19f":{
      "scriptId":"u21"},
    "6ffc8efe3df04122ad454e085335677e":{
      "scriptId":"u22"},
    "b5ae69201dc3449d83d28fd8eb671a51":{
      "scriptId":"u23",
      "fc1cde7cbfd44a429c63bc03d2dad238":{
        "scriptId":"u24"},
      "d541aa5abb104593ade50bf5a901d62a":{
        "scriptId":"u25"},
      "48c043db19e443daaad28b6565e9af35":{
        "scriptId":"u26"},
      "5652abe7da524d7da0ee59ff511d08e3":{
        "scriptId":"u27"},
      "4bd8bc1c9de9428c9013ab06e59631c4":{
        "scriptId":"u28"},
      "afa01676eda8434c8bc3894106940c4e":{
        "scriptId":"u29"}},
    "b85ff612a05c4016bd883358c1bba49a":{
      "scriptId":"u30"},
    "d3eb851e6494480da6c3f4b4f4a33b3f":{
      "scriptId":"u31"},
    "be57c01fe8af4ded85a729ba2dd16891":{
      "scriptId":"u32"},
    "1ee9b7e4b61e4418b63985cb0d677422":{
      "scriptId":"u33"}}});